# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ojs_locale.locale_listener:
        class: AppBundle\Services\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    app.user.registration.form.type:
        class: UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias:  app_user_registration }