<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTimelineRepository extends EntityRepository {
    
}
