<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventoryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryItemRepository extends EntityRepository {
    
}
